services:
  postgres:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: gitstats
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    entrypoint: ["docker-entrypoint.sh" , "postgres", "-c", "log_statement=all"]
